In [5]:
#Q1
import numpy as np
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warn

In [7]:
#Q2
arr1=np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Q3
arr2=arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
#Q4: la forme(shape)
arr2.shape

(2, 5)

In [10]:
#le nombre des dimensions
arr2.ndim
#la taille de chaque element en octet
arr2.size

10

In [12]:
#Q5
arr3=np.ones((3,3),dtype="bool")
arr3

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
#Q6
arr4=np.random.randint(0,10,(4,4))
arr4

array([[3, 5, 9, 6],
       [1, 4, 5, 6],
       [2, 8, 7, 4],
       [7, 3, 8, 6]], dtype=int32)

In [16]:
#Q7
res=arr4[1::2,::2]
print(res)

[[1 5]
 [7 8]]


In [17]:
#Q8
arr4[:2, :2]
arr4

array([[3, 5, 9, 6],
       [1, 4, 5, 6],
       [2, 8, 7, 4],
       [7, 3, 8, 6]], dtype=int32)